# Czech to English TV Series Title Mapping
# This helps find series when searching with Czech names

CZECH_TO_ENGLISH_MAPPING = {
    # Popular series
    "zoufalé manželky": "desperate housewives",
    "zoufale manzelky": "desperate housewives", 
    "perníkový táta": "breaking bad",
    "pernikovy tata": "breaking bad",
    "hra o trůny": "game of thrones",
    "hra o truny": "game of thrones",
    "přátelé": "friends",
    "pratele": "friends",
    "teorie velkého třesku": "the big bang theory",
    "teorie velkeho tresku": "the big bang theory",
    "kanceláři": "the office",
    "kancelari": "the office",
    "jak jsem poznal vaši matku": "how i met your mother",
    "jak jsem poznal vasi matku": "how i met your mother",
    "sherlock holmes": "sherlock",
    "doktor who": "doctor who",
    "ztraceni": "lost",
    "krimi las vegas": "csi crime scene investigation",
    "krimi miami": "csi miami",
    "krimi new york": "csi ny",
    "simpsonovi": "the simpsons",
    "futurama": "futurama",
    "familia guy": "family guy",
    "south park": "south park",
    "supernatural": "supernatural",
    "nadpřirozeno": "supernatural",
    "nadprirozeno": "supernatural",
    "walking dead": "the walking dead",
    "chodící mrtví": "the walking dead",
    "chudici mrtvi": "the walking dead",
    "house": "house md",
    "doktor house": "house md",
    "mentalist": "the mentalist",
    "castle": "castle",
    "bones": "bones",
    "kostlivci": "bones",
    "ncis": "ncis",
    "criminal minds": "criminal minds",
    "kriminální mysli": "criminal minds",
    "kriminalni mysli": "criminal minds",
    "dexter": "dexter",
    "24": "24",
    "prison break": "prison break",
    "útěk z vězení": "prison break",
    "utek z vezeni": "prison break",
    "heroes": "heroes",
    "hrdinové": "heroes",
    "hrdinove": "heroes",
    "glee": "glee",
    "stranger things": "stranger things",
    "podivné věci": "stranger things",
    "podivne veci": "stranger things",
    "black mirror": "black mirror",
    "černé zrcadlo": "black mirror",
    "cerne zrcadlo": "black mirror",
    "westworld": "westworld",
    "západní svět": "westworld",
    "zapadni svet": "westworld",
    "vikings": "vikings",
    "vikingové": "vikings",
    "vikingove": "vikings",
    "arrow": "arrow",
    "šíp": "arrow",
    "sip": "arrow",
    "flash": "the flash",
    "narcos": "narcos",
    "better call saul": "better call saul",
    "lepší volat saulovi": "better call saul",
    "lepsi volat saulovi": "better call saul"
}